name: Yarn CI
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn
      - name: Test
        run: yarn test
        env:
          CI: true
      - name: Build
        run: yarn build
